### ISSUE TITLE
calibgrid not compiling under cygwin

### ISSUE THREAD

**Issue by arnonm** [arpg/Calibu#47]
Having problems compiling calibgrid, rest of project compiles.
[ 71%] Built target calibu
[ 76%] Building CXX object applications/calib/CMakeFiles/calibgrid.dir/main.cpp.o
In file included from /cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:9:0:
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h: In member function ‘void calibu::Calibrator::AddObservation(std::size_t, std::size_t, const Vector3d&, const Vector2d&)’:
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:201:26: error: ‘FovCamera’ does not name a type
         if( dynamic_cast<FovCamera<double>* >(interface.get()) ) {
                          ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:201:35: error: expected ‘>’ before ‘<’ token
         if( dynamic_cast<FovCamera<double>* >(interface.get()) ) {
                                   ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:201:35: error: expected ‘(’ before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:201:35: error: expected primary-expression before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:201:36: error: expected primary-expression before ‘double’
         if( dynamic_cast<FovCamera<double>* >(interface.get()) ) {
                                    ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:201:36: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:201:36: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:202:85: error: ‘FovCamera’ was not declared in this scope
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<FovCamera<double>>,
                                                                                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:202:101: error: template argument 1 is invalid
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<FovCamera<double>>,
                                                                                                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:204:21: error: ‘FovCamera’ is not a member of ‘calibu’
                     calibu::FovCamera<double>::NumParams>( new ReprojectionCostFunctor<FovCamera<double>>(P_w, p_c) );
                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:204:21: error: ‘FovCamera’ is not a member of ‘calibu’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:204:45: error: template argument 1 is invalid
                     calibu::FovCamera<double>::NumParams>( new ReprojectionCostFunctor<FovCamera<double>>(P_w, p_c) );
                                             ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:204:45: error: template argument 5 is invalid
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:205:33: error: ‘Poly2Camera’ does not name a type
         } else if( dynamic_cast<Poly2Camera<double>* >(interface.get()) ) {
                                 ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:205:44: error: expected ‘>’ before ‘<’ token
         } else if( dynamic_cast<Poly2Camera<double>* >(interface.get()) ) {
                                            ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:205:44: error: expected ‘(’ before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:205:44: error: expected primary-expression before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:205:45: error: expected primary-expression before ‘double’
         } else if( dynamic_cast<Poly2Camera<double>* >(interface.get()) ) {
                                             ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:205:45: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:205:45: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:206:85: error: ‘Poly2Camera’ was not declared in this scope
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<Poly2Camera<double>>,
                                                                                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:206:103: error: template argument 1 is invalid
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<Poly2Camera<double>>,
                                                                                                       ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:208:21: error: ‘Poly2Camera’ is not a member of ‘calibu’
                     calibu::Poly2Camera<double>::NumParams>( new ReprojectionCostFunctor<Poly2Camera<double>>(P_w, p_c) );
                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:208:21: error: ‘Poly2Camera’ is not a member of ‘calibu’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:208:47: error: template argument 1 is invalid
                     calibu::Poly2Camera<double>::NumParams>( new ReprojectionCostFunctor<Poly2Camera<double>>(P_w, p_c) );
                                               ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:208:47: error: template argument 5 is invalid
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:209:33: error: ‘LinearCamera’ does not name a type
         } else if( dynamic_cast<LinearCamera<double>* >(interface.get()) ) {
                                 ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:209:45: error: expected ‘>’ before ‘<’ token
         } else if( dynamic_cast<LinearCamera<double>* >(interface.get()) ) {
                                             ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:209:45: error: expected ‘(’ before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:209:45: error: expected primary-expression before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:209:46: error: expected primary-expression before ‘double’
         } else if( dynamic_cast<LinearCamera<double>* >(interface.get()) ) {
                                              ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:209:46: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:209:46: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:210:85: error: ‘LinearCamera’ was not declared in this scope
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<LinearCamera<double>>,
                                                                                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:210:104: error: template argument 1 is invalid
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<LinearCamera<double>>,
                                                                                                        ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:212:21: error: ‘LinearCamera’ is not a member of ‘calibu’
                     calibu::LinearCamera<double>::NumParams>( new ReprojectionCostFunctor<LinearCamera<double>>(P_w, p_c) );
                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:212:21: error: ‘LinearCamera’ is not a member of ‘calibu’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:212:48: error: template argument 1 is invalid
                     calibu::LinearCamera<double>::NumParams>( new ReprojectionCostFunctor<LinearCamera<double>>(P_w, p_c) );
                                                ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:212:48: error: template argument 5 is invalid
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:213:33: error: ‘Poly3Camera’ does not name a type
         } else if( dynamic_cast<Poly3Camera<double>* >(interface.get()) ) {
                                 ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:213:44: error: expected ‘>’ before ‘<’ token
         } else if( dynamic_cast<Poly3Camera<double>* >(interface.get()) ) {
                                            ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:213:44: error: expected ‘(’ before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:213:44: error: expected primary-expression before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:213:45: error: expected primary-expression before ‘double’
         } else if( dynamic_cast<Poly3Camera<double>* >(interface.get()) ) {
                                             ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:213:45: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:213:45: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:214:85: error: ‘Poly3Camera’ was not declared in this scope
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<Poly3Camera<double>>,
                                                                                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:214:103: error: template argument 1 is invalid
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<Poly3Camera<double>>,
                                                                                                       ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:216:21: error: ‘Poly3Camera’ is not a member of ‘calibu’
                     calibu::Poly3Camera<double>::NumParams>( new ReprojectionCostFunctor<Poly3Camera<double>>(P_w, p_c) );
                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:216:21: error: ‘Poly3Camera’ is not a member of ‘calibu’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:216:47: error: template argument 1 is invalid
                     calibu::Poly3Camera<double>::NumParams>( new ReprojectionCostFunctor<Poly3Camera<double>>(P_w, p_c) );
                                               ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:216:47: error: template argument 5 is invalid
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:217:33: error: ‘KannalaBrandtCamera’ does not name a type
         } else if( dynamic_cast<KannalaBrandtCamera<double>* >(interface.get()) ) {
                                 ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:217:52: error: expected ‘>’ before ‘<’ token
         } else if( dynamic_cast<KannalaBrandtCamera<double>* >(interface.get()) ) {
                                                    ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:217:52: error: expected ‘(’ before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:217:52: error: expected primary-expression before ‘<’ token
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:217:53: error: expected primary-expression before ‘double’
         } else if( dynamic_cast<KannalaBrandtCamera<double>* >(interface.get()) ) {
                                                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:217:53: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:217:53: error: expected ‘)’ before ‘double’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:218:85: error: ‘KannalaBrandtCamera’ was not declared in this scope
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<KannalaBrandtCamera<double>>,
                                                                                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:218:111: error: template argument 1 is invalid
             cost->Cost() =  new ceres::AutoDiffCostFunction<ReprojectionCostFunctor<KannalaBrandtCamera<double>>,
                                                                                                               ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:220:21: error: ‘KannalaBrandtCamera’ is not a member of ‘calibu’
                     calibu::KannalaBrandtCamera<double>::NumParams>( new ReprojectionCostFunctor<KannalaBrandtCamera<double>>(P_w, p_c) );
                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:220:21: error: ‘KannalaBrandtCamera’ is not a member of ‘calibu’
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:220:55: error: template argument 1 is invalid
                     calibu::KannalaBrandtCamera<double>::NumParams>( new ReprojectionCostFunctor<KannalaBrandtCamera<double>>(P_w, p_c) );
                                                       ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:220:55: error: template argument 5 is invalid
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp: In function ‘int main(int, char**)’:
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:125:3: error: ‘VideoInput’ is not a member of ‘pangolin’
   pangolin::VideoInput video(video_uri);
   ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:128:30: error: ‘video’ was not declared in this scope
   unsigned char image_buffer[video.SizeBytes()];
                              ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:174:33: error: ‘FovCamera’ was not declared in this scope
         Eigen::VectorXd params_(FovCamera<double>::NumParams);
                                 ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:174:43: error: expected primary-expression before ‘double’
         Eigen::VectorXd params_(FovCamera<double>::NumParams);
                                           ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:177:67: error: ‘FovCamera’ does not name a type
         std::shared_ptr<CameraInterface<double>> starting_cam(new FovCamera<double>(params_, size_));
                                                                   ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:177:77: error: expected primary-expression before ‘double’
         std::shared_ptr<CameraInterface<double>> starting_cam(new FovCamera<double>(params_, size_));
                                                                             ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:181:33: error: ‘Poly2Camera’ was not declared in this scope
         Eigen::VectorXd params_(Poly2Camera<double>::NumParams);
                                 ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:181:45: error: expected primary-expression before ‘double’
         Eigen::VectorXd params_(Poly2Camera<double>::NumParams);
                                             ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:184:67: error: ‘Poly2Camera’ does not name a type
         std::shared_ptr<CameraInterface<double>> starting_cam(new Poly2Camera<double>(params_, size_));
                                                                   ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:184:79: error: expected primary-expression before ‘double’
         std::shared_ptr<CameraInterface<double>> starting_cam(new Poly2Camera<double>(params_, size_));
                                                                               ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:188:33: error: ‘Poly3Camera’ was not declared in this scope
         Eigen::VectorXd params_(Poly3Camera<double>::NumParams);
                                 ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:188:45: error: expected primary-expression before ‘double’
         Eigen::VectorXd params_(Poly3Camera<double>::NumParams);
                                             ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:191:67: error: ‘Poly3Camera’ does not name a type
         std::shared_ptr<CameraInterface<double>> starting_cam(new Poly3Camera<double>(params_, size_));
                                                                   ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:191:79: error: expected primary-expression before ‘double’
         std::shared_ptr<CameraInterface<double>> starting_cam(new Poly3Camera<double>(params_, size_));
                                                                               ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:195:33: error: ‘KannalaBrandtCamera’ was not declared in this scope
         Eigen::VectorXd params_(KannalaBrandtCamera<double>::NumParams);
                                 ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:195:53: error: expected primary-expression before ‘double’
         Eigen::VectorXd params_(KannalaBrandtCamera<double>::NumParams);
                                                     ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:198:67: error: ‘KannalaBrandtCamera’ does not name a type
         std::shared_ptr<CameraInterface<double>> starting_cam(new KannalaBrandtCamera<double>(params_, size_));
                                                                   ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:198:87: error: expected primary-expression before ‘double’
         std::shared_ptr<CameraInterface<double>> starting_cam(new KannalaBrandtCamera<double>(params_, size_));
                                                                                       ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:251:19: error: size of array ‘calib_cams’ is not an integral constant-expression
   int calib_cams[N];
                   ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:252:23: error: size of array ‘tracking_good’ is not an integral constant-expression
   bool tracking_good[N];
                       ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:266:31: error: ‘FovCamera’ was not declared in this scope
       Eigen::VectorXd params_(FovCamera<double>::NumParams);
                               ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:266:41: error: expected primary-expression before ‘double’
       Eigen::VectorXd params_(FovCamera<double>::NumParams);
                                         ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:269:39: error: template argument 1 is invalid
       std::shared_ptr<FovCamera<double>>
                                       ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:270:28: error: ‘FovCamera’ does not name a type
           starting_cam(new FovCamera<double>(params_, size_));
                            ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:270:38: error: expected primary-expression before ‘double’
           starting_cam(new FovCamera<double>(params_, size_));
                                      ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:272:74: error: no matching function for call to ‘calibu::Calibrator::AddCamera(int&, Sophus::SE3d)’
       calib_cams[i] = calibrator.AddCamera( starting_cam, Sophus::SE3d() );
                                                                          ^
In file included from /cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:9:0:
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:147:9: note: candidate: int calibu::Calibrator::AddCamera(std::shared_ptr<calibu::CameraInterface<double> >, const SE3d&)
     int AddCamera(const std::shared_ptr<CameraInterface<double>> cam,
         ^
/cygdrive/c/Users/meshulam/workspace/Calibu/include/calibu/calib/Calibrator.h:147:9: note:   no known conversion for argument 1 from ‘int’ to ‘std::shared_ptr<calibu::CameraInterface<double> >’
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:320:30: error: size of array ‘tex’ is not an integral constant-expression
     pangolin::GlTexture tex[N];
                              ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:372:24: error: ‘image_buffer’ was not declared in this scope
         if( video.Grab(image_buffer, images, true, true) ) {
                        ^
/cygdrive/c/Users/meshulam/workspace/Calibu/applications/calib/main.cpp:565:35: error: ‘image_buffer’ was not declared in this scope
     bool valid_frame = video.Grab(image_buffer, images, true, true);
                                   ^
ccmake applications/calib/CMakeFiles/calibgrid.dir/build.make:62: recipe for target 'applications/calib/CMakeFiles/calibgrid.dir/main.cpp.o' failed
make[2]: *** [applications/calib/CMakeFiles/calibgrid.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'applications/calib/CMakeFiles/calibgrid.dir/all' failed
make[1]: *** [applications/calib/CMakeFiles/calibgrid.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

CmakeCache.txt
# This is the CMakeCache file.
# For build in directory: /cygdrive/c/Users/meshulam/workspace/Calibu/build
# It was generated by CMake: /usr/bin/cmake.exe
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
# KEY:TYPE=VALUE
# KEY is the name of a variable in the cache.
# TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
# VALUE is the current value for the KEY.

########################
# EXTERNAL cache entries
########################

//Build Applications
BUILD_APPLICATIONS:BOOL=ON

//OFF
BUILD_CALIBGRID:BOOL=ON

//Build MATLAB wrappers.
BUILD_MATLAB:BOOL=OFF

//Build Shared Library
BUILD_SHARED_LIBS:BOOL=ON

//Choose the type of build, options are: None(CMAKE_CXX_FLAGS or
// CMAKE_C_FLAGS used) Debug Release RelWithDebInfo MinSizeRel.
CMAKE_BUILD_TYPE:STRING=

//Enable/Disable color output during build.
CMAKE_COLOR_MAKEFILE:BOOL=ON

//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=

//Flags used by the compiler during debug builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=-g

//Flags used by the compiler during release builds for minimum
// size.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
"CMakeCache.txt" 398 lines, 15462 characters
//Flags used by the compiler during release builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the compiler during release builds with debug info.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

//Flags used by the compiler during all build types.
CMAKE_C_FLAGS:STRING=

//Flags used by the compiler during debug builds.
CMAKE_C_FLAGS_DEBUG:STRING=-g

//Flags used by the compiler during release builds for minimum
// size.
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the compiler during release builds.
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the compiler during release builds with debug info.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

//Flags used by the linker.
CMAKE_EXE_LINKER_FLAGS:STRING=-Wl,--enable-auto-import

//Flags used by the linker during debug builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Enable/Disable output of compile commands during generation.
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF

//Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=/usr/local

CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make.exe

//Flags used by the linker during the creation of modules.
CMAKE_MODULE_LINKER_FLAGS:STRING=

//Flags used by the linker during debug builds.
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=Calibu

//Flags for Windows Resource Compiler.
CMAKE_RC_FLAGS:STRING=' '

//Flags used by the linker during the creation of dll's.
CMAKE_SHARED_LINKER_FLAGS:STRING=

//Flags used by the linker during debug builds.
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//If set, runtime paths are not added when installing shared libraries,
// but are added when building.
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
//If set, runtime paths are not added when using shared libraries.
CMAKE_SKIP_RPATH:BOOL=NO

//Flags used by the linker during the creation of static libraries.
CMAKE_STATIC_LINKER_FLAGS:STRING=

//Flags used by the linker during debug builds.
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//If true, cmake will use relative paths in makefiles and projects.
CMAKE_USE_RELATIVE_PATHS:BOOL=OFF

//If this value is on, makefiles will be generated without the
// .SILENT directive, and all commands will be echoed to the console
// during the make.  This is useful for debugging only. With Visual
// Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE

//The directory containing a CMake configuration file for CVars.
CVars_DIR:PATH=/usr/local/lib/cmake/CVars

//Value Computed by CMake
Calibu_BINARY_DIR:STATIC=/cygdrive/c/Users/meshulam/workspace/Calibu/build

//Value Computed by CMake
Calibu_SOURCE_DIR:STATIC=/cygdrive/c/Users/meshulam/workspace/Calibu

//The directory containing a CMake configuration file for Ceres.
Ceres_DIR:PATH=/usr/local/lib/cmake/Ceres

//Path to a file.
EIGEN3_INCLUDE_DIR:PATH=/usr/local/include/eigen3

//Path to a file.
EIGEN_INCLUDE_DIR:PATH=/usr/local/include/eigen3

//Should the Calibu package be exported for use by other software
EXPORT_Calibu:BOOL=ON

//Path to a file.
GLOG_INCLUDE_DIR:PATH=/usr/local/include

//Path to a library.
GLOG_LIBRARY:FILEPATH=/usr/local/lib/libglog.a

//Path where debug 3rdpaty OpenCV dependencies are located
OpenCV_3RDPARTY_LIB_DIR_DBG:PATH=

//Path where release 3rdpaty OpenCV dependencies are located
OpenCV_3RDPARTY_LIB_DIR_OPT:PATH=

OpenCV_CONFIG_PATH:FILEPATH=/usr/lib/cmake/opencv

//The directory containing a CMake configuration file for OpenCV.
OpenCV_DIR:PATH=/usr/lib/cmake/opencv

//Path where debug OpenCV libraries are located
OpenCV_LIB_DIR_DBG:PATH=

//Path where release OpenCV libraries are located
OpenCV_LIB_DIR_OPT:PATH=

//The directory containing a CMake configuration file for Pangolin.
Pangolin_DIR:PATH=/usr/local/lib/cmake/Pangolin

//The directory containing a CMake configuration file for Sophus.
Sophus_DIR:PATH=/usr/local/lib/cmake/Sophus

//Path to a file.
TINYXML_INCLUDE_DIR:PATH=/usr/include

//Path to a library.
TINYXML_LIBRARY:FILEPATH=/usr/lib/libtinyxml.dll.a

//Dependencies for the target
calibu_LIB_DEPENDS:STATIC=general;/usr/lib/libtinyxml.dll.a;general;opencv_core;general;opencv_calib3d;

**Comment by crheckman** [comment]
Hi there,

None of us here have significant experience with Cygwin, but to respond to this issue directly, we don't support calibgrid anymore. I would recommend using vicalib for your purposes, which accomplishes the same task and is also in our repo.
