### ISSUE TITLE
Inconsistent Randomness Across Platforms

### ISSUE THREAD

**Issue by Hippocrates** [arpg/Calibu#51]
Feel free to take or leave this, I'm just putting this up here because it just bit me today since I was generating targets on one platform, while trying to identify them with another.

Because there's no standardization of how to do random uniform distributions in the C++ standard, the random targets produced by the same grid/seed combinations have no guarantee to be the same between different implementations of the standard library.

The specific issue is at https://github.com/arpg/Calibu/blob/master/src/target/RandomGrid.cpp#L94. My solution was to simply change it to:

`M(r,c) = rng() % 2;`

Perhaps a little inelegant, but it ensures consistently generated targets across platforms.

Like I said, feel free to ignore this if you think its too esoteric or you don't want to break backwards compatibility with existing applications (this is definitely _not_ how libstdc++ implements uniform int distribution).

**Comment by crheckman** [comment]
Thanks for this contribution. It would be good to address this; at the same time, I'm wary of potentially breaking libstdc++ compatibility. @mcguire-steve, would you have an alternative suggestion?

**Comment by mcguire-steve** [comment]
Agree with the sentiment. Would need to do some background research
first... Immediate thoughts: might be something usable in Boost, e.g. to
stabilize cross-platform operation. Would want to test across several
targets: x64 Linux, MacOS  versions, ARM7a Linux, etc before declaring
success.

**Comment by gsibley** [comment]
Not sure we care about backwards compatibility with libstdc++.  We
definitely care about cross-platform consistency.  Boost is not a
dependency we should entertain.  At first cut the proposal looks fine to me.

**Comment by Hippocrates** [comment]
I'd agree that adding boost as a dependency is a little heavyweight for this particular instance. The solution I've provided is "correct" in that it will create a uniform 1-bit distribution from an n-bit distribution (which MT does), so if that's your only criteria, and you don't mind breaking backwards compatibility, that's probably your best bet in terms of time spent to results obtained.

Mostly, I was thinking that if you wanted to keep compatibility with libstdc++ (specifically, libstdc++ _in its current state_, because how it does `unitform_int_distribution` could theoretically change even between different releases!) for the sake of people who have already printed off targets using your system, then maybe you might look over the current state of the source code and port in their integer distribution code here. 

Personally, I don't have any problem re-printing my targets, but I can't speak for other users.

**Comment by JStech** [comment]
Can't we just implement a simple LCG? We don't need a cryptographic PRNG.

**Comment by gsibley** [comment]
+1 simple LCG

On Fri, Jul 22, 2016 at 1:55 PM, John Stechschulte <notifications@github.com

**Comment by crheckman** [comment]
After a discussion with @mcguire-steve, we both agree that the proposed solution by @Hippocrates certainly addresses the topic at hand and does not step us backward in any compatibility that currently exists. A simple LCG is not necessary to address the compatibility issue mentioned.

Any solution, even that proposed by @JStech, will break backward compatibility, which I think all of us here are OK with.

For what it's worth, this is not a use case we've extensively tested and it may need to be revisited for other architectures if we want true cross-platform compatibility. A simple LCG might address this but any implementation would require extensive testing as well.
