### ISSUE TITLE
TinyXML Error

### ISSUE THREAD

**Issue by soulslicer** [arpg/Calibu#54]
I seem to be getting the following error when compiling:

../../libcalibu.so: undefined reference to `tinyxml2::StrPair::GetStr()'

I have the latest master of TinyXML2 built and installed and I've checked if it was linking the paths correctly

**Comment by soulslicer** [comment]
Strange, turns out I had to hack the TinyXML library and move the implementation directly into the header file for it to work.

**Comment by chaiban** [comment]
Hi @soulslicer ,

I am getting this error.

../../libcalibu.so: undefined reference to `tinyxml2::XMLDocument::ErrorStr() const'

can you explain how you cleared your error ? may be i can clear it in similar way. 

Thank you.
